openapi: 3.0.3
info:
  title: Event Management Microservice API
  version: 1.3.0 # Version bumped to reflect new feature
  description: >
    API for managing the full lifecycle of events, including sessions, speakers, venues, registrations, and presentations.
    All resources are scoped to an organization for strict data isolation.
servers:
  - url: http://localhost:8000/api/events/v1
    description: Local development server for Events Service
security:
  - BearerAuth: []
tags:
  - name: Events
  - name: Sessions
  - name: Presentations # --- NEW ---
  - name: Registrations
  - name: Speakers
  - name: Venues
  - name: Public
  - name: Internal

paths:
  # ... All existing paths for Events, Public, etc. remain the same ...

  /organizations/{orgId}/events/{eventId}/sessions:
    # ... The existing GET and POST for listing/creating sessions are here ...
    get:
      # ...
    post:
      # ...

  #
  # ... All other paths remain the same ...

# --- Reusable Components ---
components:
  # ... All existing securitySchemes, responses, etc. remain the same ...

  parameters:
    # ... All existing parameters ...
    SessionIdPath: # --- NEW ---
      name: sessionId
      in: path
      required: true
      schema: { type: string }

  schemas:
    # --- NEW SCHEMA ---
    Presentation:
      type: object
      properties:
        id: { type: string, readOnly: true }
        session_id: { type: string, readOnly: true }
        slide_urls:
          type: array
          items:
            type: string
            format: uri
          description: "An ordered list of public URLs for each slide image."
        createdAt: { type: string, format: "date-time", readOnly: true }

    # ... All your existing schemas (Event, Session, etc.) remain the same ...