//src/networking/recommendations/recommendations.module.ts
import { Module } from '@nestjs/common';
import { RecommendationsController } from './recommendations.controller';
import { RecommendationsService } from './recommendations.service';
import { RecommendationsListener } from './recommendations.listener';
import { RecommendationsScheduler } from './recommendations.scheduler';
import { FeedbackController } from './feedback.controller';
import { FeedbackService } from './feedback.service';
import { PrismaModule } from 'src/prisma.module';
import { SharedModule } from 'src/shared/shared.module';

/**
 * Recommendations Module
 *
 * Provides AI-powered attendee matchmaking recommendations.
 * Integrates with oracle-ai-service for LLM-based matching.
 *
 * Features:
 * - Personalized recommendations based on goals, interests, skills
 * - Conversation starters generated by LLM
 * - Redis caching for fast access
 * - Analytics tracking for recommendation quality
 * - Event-driven triggers (check-in, session join)
 * - Scheduled daily refresh and cleanup tasks
 * - Feedback collection for continuous improvement
 */
@Module({
  imports: [PrismaModule, SharedModule],
  controllers: [RecommendationsController, FeedbackController],
  providers: [
    RecommendationsService,
    RecommendationsListener,
    RecommendationsScheduler,
    FeedbackService,
  ],
  exports: [RecommendationsService, FeedbackService],
})
export class RecommendationsModule {}
