"""Add owner_id to events table

Revision ID: 97624f6f2e46
Revises: e33560ce950d # <-- Make sure this matches the previous revision ID in your file
Create Date: 2025-09-20 21:50:00.123456

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "97624f6f2e46"
down_revision: Union[str, None] = "e33560ce950d"  # <-- Make sure this matches
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("events", sa.Column("owner_id", sa.String(), nullable=False))
    op.create_index(op.f("ix_events_owner_id"), "events", ["owner_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_events_owner_id"), table_name="events")
    op.drop_column("events", "owner_id")
    # ### end Alembic commands ###
