"""Migrations of all models of the Event-Lifecycle service

Revision ID: b27ba454decb
Revises:
Create Date: 2025-08-05 01:49:03.174746

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b27ba454decb"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "events",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("organization_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("start_date", sa.DateTime(), nullable=False),
        sa.Column("end_date", sa.DateTime(), nullable=False),
        sa.Column("venue_id", sa.String(), nullable=True),
        sa.Column(
            "is_public", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "is_archived", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "createdAt", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updatedAt", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("imageUrl", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_events_organization_id"), "events", ["organization_id"], unique=False
    )

    op.create_table(
        "venues",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("organization_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("address", sa.String(), nullable=True),
        sa.Column(
            "is_archived", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_venues_organization_id"), "venues", ["organization_id"], unique=False
    )

    op.create_table(
        "speakers",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("organization_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("bio", sa.String(), nullable=True),
        sa.Column("expertise", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column(
            "is_archived", sa.String(), server_default=sa.text("false"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_speakers_organization_id"),
        "speakers",
        ["organization_id"],
        unique=False,
    )

    op.create_table(
        "event_blueprints",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("organization_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("template", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "is_archived", sa.String(), server_default=sa.text("false"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_event_blueprints_organization_id"),
        "event_blueprints",
        ["organization_id"],
        unique=False,
    )

    op.create_table(
        "sessions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("event_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=False),
        sa.Column(
            "is_archived", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sessions_event_id"), "sessions", ["event_id"], unique=False
    )

    op.create_table(
        "ads",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("organization_id", sa.String(), nullable=False),
        sa.Column("event_id", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("content_type", sa.String(), nullable=False),
        sa.Column("media_url", sa.String(), nullable=False),
        sa.Column("click_url", sa.String(), nullable=False),
        sa.Column(
            "is_archived", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ads_event_id"), "ads", ["event_id"], unique=False)
    op.create_index(
        op.f("ix_ads_organization_id"), "ads", ["organization_id"], unique=False
    )

    op.create_table(
        "domain_events",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("event_id", sa.String(), nullable=False),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_domain_events_event_id"), "domain_events", ["event_id"], unique=False
    )

    op.create_table(
        "offers",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("organization_id", sa.String(), nullable=False),
        sa.Column("event_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("original_price", sa.Float(), nullable=True),
        sa.Column("currency", sa.String(), nullable=False),
        sa.Column("offer_type", sa.String(), nullable=False),
        sa.Column("image_url", sa.String(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "is_archived", sa.String(), server_default=sa.text("false"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_offers_event_id"), "offers", ["event_id"], unique=False)
    op.create_index(
        op.f("ix_offers_organization_id"), "offers", ["organization_id"], unique=False
    )

    op.create_table(
        "registrations",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("event_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("guest_email", sa.String(), nullable=True),
        sa.Column("guest_name", sa.String(), nullable=True),
        sa.Column("ticket_code", sa.String(), nullable=False),
        sa.Column("checked_in_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "confirmed", "cancelled", "checked_in", name="registration_status_enum"
            ),
            server_default="confirmed",
            nullable=False,
        ),
        sa.Column(
            "is_archived", sa.String(), server_default=sa.text("false"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_registrations_event_id"), "registrations", ["event_id"], unique=False
    )
    op.create_index(
        op.f("ix_registrations_guest_email"),
        "registrations",
        ["guest_email"],
        unique=False,
    )
    op.create_index(
        op.f("ix_registrations_ticket_code"),
        "registrations",
        ["ticket_code"],
        unique=True,
    )
    op.create_index(
        op.f("ix_registrations_user_id"), "registrations", ["user_id"], unique=False
    )

    op.create_table(
        "presentations",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("slide_urls", postgresql.ARRAY(sa.String()), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id"),
    )

    op.create_table(
        "session_speaker_association",
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("speaker_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["speaker_id"],
            ["speakers.id"],
        ),
        sa.PrimaryKeyConstraint("session_id", "speaker_id"),
    )

    op.create_table(
        "waitlist_entries",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_waitlist_entries_session_id"),
        "waitlist_entries",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_waitlist_entries_user_id"),
        "waitlist_entries",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_waitlist_entries_user_id"), table_name="waitlist_entries")
    op.drop_index(op.f("ix_waitlist_entries_session_id"), table_name="waitlist_entries")
    op.drop_table("waitlist_entries")
    op.drop_table("session_speaker_association")
    op.drop_table("presentations")
    op.drop_index(op.f("ix_registrations_user_id"), table_name="registrations")
    op.drop_index(op.f("ix_registrations_ticket_code"), table_name="registrations")
    op.drop_index(op.f("ix_registrations_guest_email"), table_name="registrations")
    op.drop_index(op.f("ix_registrations_event_id"), table_name="registrations")
    op.drop_table("registrations")
    op.drop_index(op.f("ix_offers_organization_id"), table_name="offers")
    op.drop_index(op.f("ix_offers_event_id"), table_name="offers")
    op.drop_table("offers")
    op.drop_index(op.f("ix_domain_events_event_id"), table_name="domain_events")
    op.drop_table("domain_events")
    op.drop_index(op.f("ix_ads_organization_id"), table_name="ads")
    op.drop_index(op.f("ix_ads_event_id"), table_name="ads")
    op.drop_table("ads")
    op.drop_index(op.f("ix_sessions_event_id"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_index(
        op.f("ix_event_blueprints_organization_id"), table_name="event_blueprints"
    )
    op.drop_table("event_blueprints")
    op.drop_index(op.f("ix_speakers_organization_id"), table_name="speakers")
    op.drop_table("speakers")
    op.drop_index(op.f("ix_venues_organization_id"), table_name="venues")
    op.drop_table("venues")
    op.drop_index(op.f("ix_events_organization_id"), table_name="events")
    op.drop_table("events")
    # ### end Alembic commands ###
