name: Real-Time Service CI

on:
  push:
    branches: [ "main" ]
    # **FIX**: Only trigger this workflow for changes in the real-time-service directory
    paths:
      - 'real-time-service/**'
      - '.github/workflows/ci.yml' # Also run if the workflow file itself changes
  pull_request:
    branches: [ "main" ]
    paths:
      - 'real-time-service/**'
      - '.github/workflows/ci.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    
    # **FIX**: Tell all steps to run inside the real-time-service directory
    defaults:
      run:
        working-directory: ./real-time-service

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: youruser
          POSTGRES_PASSWORD: yourpassword
          POSTGRES_DB: yourtestdb
        ports:
          - 5435:5432
        options: >-
          --health-cmd "pg_isready -U youruser -d yourtestdb"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          # Cache npm for the specific package-lock.json
          cache: 'npm'
          cache-dependency-path: real-time-service/package-lock.json

      - name: Install dependencies
        # This now runs inside ./real-time-service
        run: npm ci

      - name: Run Unit & Integration Tests
        run: npm test

      - name: Apply Prisma Migrations to Test DB
        env:
          TEST_DATABASE_URL: postgresql://youruser:yourpassword@localhost:5435/yourtestdb
        # This also runs inside ./real-time-service and finds the prisma folder
        run: DATABASE_URL=${{ env.TEST_DATABASE_URL }} npx prisma migrate deploy

      - name: Run End-to-End Tests
        env:
          NODE_ENV: test
          TEST_DATABASE_URL: postgresql://youruser:yourpassword@localhost:5435/yourtestdb
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          REDIS_HOST: localhost
          REDIS_PORT: 6379
        run: npm run test:e2e